default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer


  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.12.1
    hooks:
    - id: black
      exclude: \.py-tpl$

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
        - pep8-naming
        args: ['--exit-zero']
